# Generated by Django 5.0.1 on 2024-01-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_alter_listing_price'),
    ]

    operations = [
    ]
